.gitignore
__tests__/helpers.test.js
config/connection.js
controllers/index.js
db/schema.sql
models/Sheet.js
models/User.js
models/index.js
server.js
utils/auth.js
utils/helpers.js
views/homepage.handlebars
views/layouts/main.handlebars
views/login.handlebars
views/partials/comments.handlebars
views/partials/post-info.handlebars
views/single-post.handlebars

Initial commit with base content that needs to be udpated

---

public/javascript/character-creator.js
views/character-creator.handlebars

#52 
Initial functionality for Character Creator page: 
- created fetch functions to retrieve race and class information from DnD Api, including: 
- Ability Bonuses
- Alignment
- Size Description
- Languages
- Proficiency Choices

character creator initial functionality

---

public/javascript/character-creator.js
views/character-creator.handlebars

Form edits: 
- Changed input field names and respective labels to more clearly reflect the information it represents, and to be more consistent throughout the form
- Changed input attribute from v-model to name. Upon research, v-model seems to be vue.js related, I figured it would be best to deal with attributes we know and understand
- In 'select' options (i.e. race, class, gender), a hidden option was added for form aesthetic purposes
- Finished adding remainder of 'races' that were missing from the options
- Finished adding remainder of 'classes' that were missing from the options
- Added 'other' option to gender select menu, just in case.
- Removed language input options as these will be filled in automatically based on the race selection
- Added input field for age and character …

Edited form fields and options to ask for necessary information for character creation

---

RENAME.env
server.js

- Updated server.js to require an env variable
- Added env variable 
- Updated RENAME.env with a placeholder

Add Session Secret as env Variable on Heroku and Locally

---

RENAME.env
controllers/home-routes.js
views/layouts/main.handlebars
views/partials/profile-details.handlebars
views/profile.handlebars

Add View for Feature/profile - If User Logged in, loads all created heros

---

controllers/api/hero-routes.js
public/javascript/character-creator.js
views/character-creator.handlebars

Changes in view/character-creator.handlebars: 
- added IDs to number inputs in form, as I had forgotten to do it earlier. 
- fixed typo in value for dwarf option in race selection.
Changes in public/javascript/character-creator.js:
- removed placeholder variables that were previously used for testing.
- changed format in which data was passed from DnD api (in retrieveRaceInfo() and retrieveClassInfo() functions) to newCharFormHandler() from individual variables to properties in an object for easier handling.
- created stringFromArray() to turn an array of language objects into a string with just the language names separated by a space - sequelize requires the use of PostgresSQL in order to store an array data type.
- created randomFromArray() to retrieve only the proficiency names from …

Functionality to create Hero from user input is DONE!

---

public/css/style.css
views/layouts/main.handlebars
views/login.handlebars

style.css - created form style for create a character page
main.handlebars - added an id and a class to the pesky p element in hopes it will go away with the right code -HELP HERE PLEASE
login.handlebars - a futile attempt and getting the pesky p element to evaporate

styled the create a character form

---

controllers/home-routes.js
public/css/style.css
seeds/seed_Hero.json
views/character-sheet-id.handlebars
views/homepage.handlebars
views/layouts/main.handlebars
views/partials/character-details.handlebars
views/partials/character-sheet-template.handlebars
views/partials/profile-details.handlebars
views/profile.handlebars

Add ALL Character Cards to Homepage, Add Unique Character Cards to Profile

---

views/layouts/main.handlebars

got favicon working

---

public/css/navigation.css
public/css/style.css
views/layouts/main.handlebars
views/partials/character-details.handlebars

Add FULL responsiveness navigational content And Hero Cards. Fixed Bug/Hamburger responsiveness

---

public/css/character-sheet-template.css
public/javascript/character-creator.js
views/partials/character-sheet-template.handlebars

- changed background of form to white to make more legible
- after submitting new character, user is taken to their profile
- changed form headers to include class, gender, and age
- proficiency bonus added dynamically
- added a section for wisdom score and modifier that was missing
- alignment description now goes in 'features and traits' section to allow more room for paragraph, and really it fits better as a personality description than an actual alignment
- dynamically added languages and proficiencies to the 'other proficiencies and languages' section
- this is gonna need further work as it doesn't look the best. I think we'll need helper functions to turn the strings back into an array and then it would display them as a list instead of all in a row.

Updated character sheet to show more of the gathered information from user input and DnD api

---

views/login.handlebars

Resolved console error on Login Page 

---

public/javascript/character-creator.js

This function takes the following information as parameters: 
- the number of proficiencies allowed, based on character class (n)
- an array of proficiencies to choose from, based on character class
The purpose of this function is to choose n amount of proficiencies, at random, from the array of proficiencies, and returns a new array with just the chosen proficiencies
- the bug: 
-sometimes it would choose duplicate proficiencies
- the fix: 
- made it so that each proficiency pushed into the new array would also get deleted from the old one so that it would no longer be available for selection.
- this caused some values to be pushed into the new array as undefined. Added an if statement to only push into the new array if the item is valid
- this would sometimes cause for less than n …

fixed randomFromArray function in character-creator.js

---

views/homepage.handlebars
views/layouts/main.handlebars
views/profile.handlebars

Fixed P element showing on multiple screens to only the homepage.

Removed Welcome Element from Login Screen

---

public/css/style.css
views/homepage.handlebars

- Edit P tag to display different messages on the homepage before and after login in.

Edit P tag display

---

public/css/character-sheet-template.css
public/css/style.css
views/partials/character-sheet-template.handlebars

Add Feature to hide a Character Sheet Until Ability Scores are Calcualted

---

controllers/home-routes.js
public/css/style.css
server.js
views/error.handlebars

created the error page!
-home-routes.js removed my pseudocode
-style.css added error styling
-server.js removed space
- built out error.handlebars

Created 404 error page

---

views/character-sheet.handlebars
views/partials/character-sheet-template-blank.handlebars

```css
<style>
.charsheet{
display: block;
}
</style>
```

Fixed Bug/blank blank sheet

---

README.md
controllers/home-routes.js
views/character-sheet.handlebars
views/hero-card.handlebars

Fixed Bug/readme URL where it was going to  https://github.com/barrantesc/The-Sheet-Show/blob/main/www.sheetshow.com

---

controllers/home-routes.js
public/css/login.css
public/javascript/login.js
public/javascript/signup.js
views/signup.handlebars

- Removed signup form from the login.handlebar and created a separate handlebar for it.
- Created a signup.js file
- added soure to home-routes.js
- edit style of button on login.css

created signup page

---

views/partials/hero-card-details.handlebars

Cleanup Hero Card by removing junk text.

---

README.md

- Moved a few technology items to be in alphabetical order
- Added additional technologies used including the new technology

Added technology to readme
